/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as HostRouteImport } from './routes/host'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CheckInRouteImport } from './routes/check-in'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MyTicketsRouteImport } from './routes/my.tickets'
import { Route as MyEventsRouteImport } from './routes/my.events'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as HostsHostIdRouteImport } from './routes/hosts.$hostId'
import { Route as EventsNewRouteImport } from './routes/events.new'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as AuthSignUpRouteImport } from './routes/auth.sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth.sign-in'
import { Route as EventsEventIdEditRouteImport } from './routes/events.$eventId_.edit'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const HostRoute = HostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckInRoute = CheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTicketsRoute = MyTicketsRouteImport.update({
  id: '/my/tickets',
  path: '/my/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const MyEventsRoute = MyEventsRouteImport.update({
  id: '/my/events',
  path: '/my/events',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const HostsHostIdRoute = HostsHostIdRouteImport.update({
  id: '/hosts/$hostId',
  path: '/hosts/$hostId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsNewRoute = EventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdEditRoute = EventsEventIdEditRouteImport.update({
  id: '/events/$eventId_/edit',
  path: '/events/$eventId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/check-in': typeof CheckInRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/host': typeof HostRoute
  '/reports': typeof ReportsRoute
  '/team': typeof TeamRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/events/new': typeof EventsNewRoute
  '/hosts/$hostId': typeof HostsHostIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/my/events': typeof MyEventsRoute
  '/my/tickets': typeof MyTicketsRoute
  '/events/$eventId/edit': typeof EventsEventIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/check-in': typeof CheckInRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/host': typeof HostRoute
  '/reports': typeof ReportsRoute
  '/team': typeof TeamRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/events/new': typeof EventsNewRoute
  '/hosts/$hostId': typeof HostsHostIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/my/events': typeof MyEventsRoute
  '/my/tickets': typeof MyTicketsRoute
  '/events/$eventId/edit': typeof EventsEventIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/check-in': typeof CheckInRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/host': typeof HostRoute
  '/reports': typeof ReportsRoute
  '/team': typeof TeamRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/events/new': typeof EventsNewRoute
  '/hosts/$hostId': typeof HostsHostIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/my/events': typeof MyEventsRoute
  '/my/tickets': typeof MyTicketsRoute
  '/events/$eventId_/edit': typeof EventsEventIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/check-in'
    | '/dashboard'
    | '/explore'
    | '/host'
    | '/reports'
    | '/team'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/events/$eventId'
    | '/events/new'
    | '/hosts/$hostId'
    | '/invite/$token'
    | '/my/events'
    | '/my/tickets'
    | '/events/$eventId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/check-in'
    | '/dashboard'
    | '/explore'
    | '/host'
    | '/reports'
    | '/team'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/events/$eventId'
    | '/events/new'
    | '/hosts/$hostId'
    | '/invite/$token'
    | '/my/events'
    | '/my/tickets'
    | '/events/$eventId/edit'
  id:
    | '__root__'
    | '/'
    | '/check-in'
    | '/dashboard'
    | '/explore'
    | '/host'
    | '/reports'
    | '/team'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/events/$eventId'
    | '/events/new'
    | '/hosts/$hostId'
    | '/invite/$token'
    | '/my/events'
    | '/my/tickets'
    | '/events/$eventId_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckInRoute: typeof CheckInRoute
  DashboardRoute: typeof DashboardRoute
  ExploreRoute: typeof ExploreRoute
  HostRoute: typeof HostRoute
  ReportsRoute: typeof ReportsRoute
  TeamRoute: typeof TeamRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  EventsNewRoute: typeof EventsNewRoute
  HostsHostIdRoute: typeof HostsHostIdRoute
  InviteTokenRoute: typeof InviteTokenRoute
  MyEventsRoute: typeof MyEventsRoute
  MyTicketsRoute: typeof MyTicketsRoute
  EventsEventIdEditRoute: typeof EventsEventIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host': {
      id: '/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof HostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-in': {
      id: '/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof CheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/tickets': {
      id: '/my/tickets'
      path: '/my/tickets'
      fullPath: '/my/tickets'
      preLoaderRoute: typeof MyTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/events': {
      id: '/my/events'
      path: '/my/events'
      fullPath: '/my/events'
      preLoaderRoute: typeof MyEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts/$hostId': {
      id: '/hosts/$hostId'
      path: '/hosts/$hostId'
      fullPath: '/hosts/$hostId'
      preLoaderRoute: typeof HostsHostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/new': {
      id: '/events/new'
      path: '/events/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof EventsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId_/edit': {
      id: '/events/$eventId_/edit'
      path: '/events/$eventId/edit'
      fullPath: '/events/$eventId/edit'
      preLoaderRoute: typeof EventsEventIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckInRoute: CheckInRoute,
  DashboardRoute: DashboardRoute,
  ExploreRoute: ExploreRoute,
  HostRoute: HostRoute,
  ReportsRoute: ReportsRoute,
  TeamRoute: TeamRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  EventsNewRoute: EventsNewRoute,
  HostsHostIdRoute: HostsHostIdRoute,
  InviteTokenRoute: InviteTokenRoute,
  MyEventsRoute: MyEventsRoute,
  MyTicketsRoute: MyTicketsRoute,
  EventsEventIdEditRoute: EventsEventIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
